secret:
  key: 1222

ping:
  period: 2
  service:
    url: https://www.baidu.com

wechat:
  cp:
    corpid:
    agentid: 1000002
    corp:
      secret:

server:
  port: 9000

white:
  list: 172.16.13.1,127.0.0.1,0:0:0:0:0:0:0:1

